author: "Chris Buckner"
namespace: custom  # default namespace, will match chart name or can be overridden

app:
  name: custom  # used for app label and service/deployment names

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30088
  name: custom-svc

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

replicas: 3