---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-html
  namespace: {{ .Release.Namespace }}
data:
  index.html: |-
{{ tpl (.Files.Get "files/html/custom-hello.html") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-resume
  namespace: {{ .Release.Namespace }}
binaryData:
  resume.pdf: {{ .Files.Get "files/resume.pdf" | b64enc | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |-
    server {
        listen {{ .Values.service.targetPort }};
        server_name _;

        location /static/ {
            root /usr/share/nginx/html;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri /index.html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
        - name: copy-html-resume
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /html/static
              cp /config-html/index.html /html/index.html
              cp /config-resume/resume.pdf /html/static/resume.pdf
          volumeMounts:
            - name: config-html-vol
              mountPath: /config-html
            - name: config-resume-vol
              mountPath: /config-resume
            - name: html-vol
              mountPath: /html
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: html-vol
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: html-vol
          emptyDir: {}
        - name: config-html-vol
          configMap:
            name: config-html
        - name: config-resume-vol
          configMap:
            name: config-resume
        - name: nginx-config
          configMap:
            name: nginx-config