apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Values.service.port }}-{{ .Values.service.targetPort }}"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-html
  namespace: {{ .Values.namespace }}
data:
  custom-hello.html: |-
{{ required "html/custom-hello.html file is required but not found!" (.Files.Get "files/html/custom-hello.html") | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: controlplane
      initContainers:
        - name: copy-and-rename
          image: busybox
          command:
            - sh
            - -c
            - |
              cp /config/custom-hello.html /html/index.html
          volumeMounts:
            - name: config-html
              mountPath: /config
            - name: www-vol
              mountPath: /html
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: www-vol
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www-vol
          emptyDir: {}
        - name: config-html
          configMap:
            name: config-html
